### PR TITLE
Switch PPO1 with PPO2

### PR DESCRIPTION
**Pull request by tomasruizt**

### CODE REVIEW

**Comment by BarisYazici** [comment]
This assert to file name prevents loading the old model file right?

**Comment by tomasruizt** [comment]
@BarisYazici The assert makes sure we don't overwrite existing tensorboard log files

**Comment by BarisYazici** [comment]
So we need to change the name of the directory if we want to load and train old model

**Comment by tomasruizt** [comment]
the model file is saved outside the tensorboard dir. If a model file exists, then we load it, otherwise, we create the agent.

**Pull request merged**
